apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esv-volume-claim
spec:
  volumeName: esv-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi