apiVersion: v1
kind: PersistentVolume
metadata:
  name: esv-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: esv-volume-claim
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "data"